[package]
name = "uniswap-v3-sdk-rs"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-dyn-abi = "0.5.4"
alloy-json-abi = "0.5.4"
alloy-primitives = "0.5.4"
alloy-sol-types = "0.5.4"
anyhow = "1.0"
num-bigint = "0.4.4"
num-traits = "0.2.17"
once_cell = "1.19.0"
ruint = "1.11.1"
uniswap-sdk-core-rust = { git = "https://github.com/malik672/uniswap-sdk-core-rust", branch = "master" }
uniswap_v3_math = "0.4.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bit_math"
harness = false

[[bench]]
name = "tick_math"
harness = false
