[package]
name = "uniswap-v3-sdk"
version = "0.7.0"
edition = "2021"
authors = ["Shuhui Luo <twitter.com/aureliano_law>"]
description = "Uniswap v3 SDK for Rust"
license = "MIT"

[dependencies]
alloy-dyn-abi = "0.5.4"
alloy-json-abi = "0.5.4"
alloy-primitives = "0.5.4"
alloy-sol-types = "0.5.4"
anyhow = "1.0"
aperture-lens = { git = "https://github.com/Aperture-Finance/Aperture-Lens", branch = "main" }
ethers = { version = "2.0", features = ["default"] }
num-bigint = "0.4.4"
num-traits = "0.2.17"
once_cell = "1.19.0"
ruint = "1.11.1"
thiserror = "1.0.53"
uniswap-sdk-core = { git = "https://github.com/malik672/uniswap-sdk-core-rust", branch = "master" }
uniswap_v3_math = "0.4.1"

[dev-dependencies]
criterion = "0.5.1"
tokio = { version = "1.35", features = ["full"] }

[[bench]]
name = "bit_math"
harness = false

[[bench]]
name = "sqrt_price_math"
harness = false

[[bench]]
name = "swap_math"
harness = false

[[bench]]
name = "tick_math"
harness = false
